[tool.poetry]
name = "earningsai"
version = "0.1.0"
description = ""
authors = ["jstammers <jimmy.stammers@gmail.com>"]
readme = "README.md"
packages = [
{ include = "earningsai"}
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.0"
jupyter = "^1.0.0"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
